name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 安装依赖
      - name: Install dependencies
        run: "pip install -r requirements.txt"

      # 运行测试
      - name: Run tests
        run: "python app.py"
